//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbBackupRecord
    {
        public int id { get; set; }
        public System.DateTime BackupDate { get; set; }
        public string FileName { get; set; }
        public string BackupType { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
