//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobDate()
        {
            this.JobDateUsers = new HashSet<JobDateUser>();
        }
    
        public int id { get; set; }
        public Nullable<int> jobid { get; set; }
        public System.DateTime jobdate1 { get; set; }
        public string location { get; set; }
        public string description { get; set; }
        public Nullable<int> jobstatusid { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual JobStatu JobStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDateUser> JobDateUsers { get; set; }
    }
}
