//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDateUser
    {
        public int id { get; set; }
        public Nullable<int> jobdateid { get; set; }
        public Nullable<int> userstudioid { get; set; }
        public decimal charge { get; set; }
    
        public virtual JobDate JobDate { get; set; }
        public virtual UserStudio UserStudio { get; set; }
    }
}
