//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class photogEntitiesLocal : DbContext
    {
        public photogEntitiesLocal()
            : base("name=photogEntitiesLocal")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Charge> Charges { get; set; }
        public virtual DbSet<ChatKey> ChatKeys { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobCharge> JobCharges { get; set; }
        public virtual DbSet<JobDate> JobDates { get; set; }
        public virtual DbSet<JobDateUser> JobDateUsers { get; set; }
        public virtual DbSet<JobStatu> JobStatus { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackageImage> PackageImages { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Studio> Studios { get; set; }
        public virtual DbSet<StudioLink> StudioLinks { get; set; }
        public virtual DbSet<StudioRole> StudioRoles { get; set; }
        public virtual DbSet<SystemRole> SystemRoles { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserStudio> UserStudios { get; set; }
        public virtual DbSet<UserSystemRole> UserSystemRoles { get; set; }
    
        public virtual int BACKUP_AZURE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BACKUP_AZURE");
        }
    
        public virtual int BACKUP_AZURE_BLOB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BACKUP_AZURE_BLOB");
        }
    
        public virtual int RESTORE_LOCAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RESTORE_LOCAL");
        }
    
        public virtual int CREATE_TBL_FROM_CLOUD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATE_TBL_FROM_CLOUD");
        }
    
        public virtual int CREATE_TBL_FROM_LOCAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATE_TBL_FROM_LOCAL");
        }
    
        public virtual int DROP_LOCAL_TBL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DROP_LOCAL_TBL");
        }
    
        public virtual int DROP_REMOTE_TBL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DROP_REMOTE_TBL");
        }
    
        public virtual int FROMCLOUD_GENERATE_CONSTRAINT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FROMCLOUD_GENERATE_CONSTRAINT");
        }
    
        public virtual int FROMCLOUD_GENERATE_FK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FROMCLOUD_GENERATE_FK");
        }
    
        public virtual int FROMLOCAL_GENERATE_CONSTRAINT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FROMLOCAL_GENERATE_CONSTRAINT");
        }
    
        public virtual int FROMLOCAL_GENERATE_FK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FROMLOCAL_GENERATE_FK");
        }
    
        public virtual int GENERATE_CONSTRAINT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERATE_CONSTRAINT");
        }
    
        public virtual int OFF_CONSTR_LOCAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OFF_CONSTR_LOCAL");
        }
    
        public virtual int OFF_CONSTR_REMOTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OFF_CONSTR_REMOTE");
        }
    
        public virtual int SELECT_LOCAL_TBL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECT_LOCAL_TBL");
        }
    
        public virtual int SELECT_REMOTE_TBL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECT_REMOTE_TBL");
        }
    }
}
