//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int id { get; set; }
        public Nullable<int> studioid { get; set; }
        [DisplayName("Package Name")]
        public string name { get; set; }
        [DisplayName("Package Price")]
        public decimal price { get; set; }
        [DisplayName("Deposit Price")]
        public decimal depositprice { get; set; }
        [DisplayName("Package Details")]
        public string details { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual Studio Studio { get; set; }
    }
}
