//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSystemRole
    {
        public int id { get; set; }
        public Nullable<int> systemroleid { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual SystemRole SystemRole { get; set; }
        public virtual User User { get; set; }
    }
}
