//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFeedback
    {
        public int id { get; set; }
        public Nullable<int> jobid { get; set; }
        public int rate { get; set; }
        public string comment { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
